title: Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "0xShivaay"
  email: "0xSivaay@proton.me"
  url: "https://0xshivaay.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "0xShivaay"
year : "2023"
